const fs = require('fs');
const path = require('path');

const envPath = path.resolve(__dirname, '../.env');
const targetDir = path.resolve(__dirname, '../src/services/firebase');
const targetFile = path.resolve(targetDir, 'env.config.ts');

// Ensure target directory exists
if (!fs.existsSync(targetDir)) {
  fs.mkdirSync(targetDir, { recursive: true });
}

let envVars = {
  FIREBASE_API_KEY: '',
  FIREBASE_AUTH_DOMAIN: '',
  FIREBASE_PROJECT_ID: '',
  FIREBASE_STORAGE_BUCKET: '',
  FIREBASE_MESSAGING_SENDER_ID: '',
  FIREBASE_APP_ID: '',
  FIREBASE_MEASUREMENT_ID: ''
};

if (fs.existsSync(envPath)) {
  const content = fs.readFileSync(envPath, 'utf8');
  content.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const parts = trimmed.split('=');
    const key = parts[0].trim();
    const val = parts.slice(1).join('=').trim().replace(/^["']|["']$/g, ''); // strip optional quotes
    if (key in envVars) {
      envVars[key] = val;
    }
  });
  console.log('✅ Loaded environment variables from .env');
} else {
  console.warn('⚠️ No .env file found at root. Using empty defaults for env.config.ts.');
}

const fileContent = `// Automatically generated by scripts/generate-env.js. Do not edit directly!
export const env = {
  FIREBASE_API_KEY: ${JSON.stringify(envVars.FIREBASE_API_KEY)},
  FIREBASE_AUTH_DOMAIN: ${JSON.stringify(envVars.FIREBASE_AUTH_DOMAIN)},
  FIREBASE_PROJECT_ID: ${JSON.stringify(envVars.FIREBASE_PROJECT_ID)},
  FIREBASE_STORAGE_BUCKET: ${JSON.stringify(envVars.FIREBASE_STORAGE_BUCKET)},
  FIREBASE_MESSAGING_SENDER_ID: ${JSON.stringify(envVars.FIREBASE_MESSAGING_SENDER_ID)},
  FIREBASE_APP_ID: ${JSON.stringify(envVars.FIREBASE_APP_ID)},
  FIREBASE_MEASUREMENT_ID: ${JSON.stringify(envVars.FIREBASE_MEASUREMENT_ID)}
};
`;

fs.writeFileSync(targetFile, fileContent, 'utf8');
console.log('✅ Generated src/services/firebase/env.config.ts');
